#!/usr/bin/env bash
set -e

# ==============================
# SIMPLE SQUID PROXY INSTALLER
# ==============================
# DITES PADA: Ubuntu/Debian (systemd)
#
# Setting tetap (hardcoded):
USERNAME="vitacimin"
PASSWORD="akuganteng123"
PORT="3128"
# ==============================

if [[ "$EUID" -ne 0 ]]; then
  echo "Jalankan script ini sebagai root (sudo)."
  exit 1
fi

echo "===> Pakai credential:"
echo "     USERNAME = ${USERNAME}"
echo "     PASSWORD = ${PASSWORD}"
echo "     PORT     = ${PORT}"
echo

echo "===> Install Squid + apache2-utils + curl..."
apt-get update -y
apt-get install -y squid apache2-utils curl

echo "===> Backup konfigurasi lama (kalau ada)..."
if [[ -f /etc/squid/squid.conf && ! -f /etc/squid/squid.conf.bak ]]; then
  cp /etc/squid/squid.conf /etc/squid/squid.conf.bak
  echo "Backup -> /etc/squid/squid.conf.bak"
fi

echo "===> Tulis konfigurasi Squid baru..."

cat >/etc/squid/squid.conf <<EOF
# =======================================
# Squid basic proxy with user:pass auth
# Generated by proxy.sh
# =======================================

# Listen port
http_port ${PORT}

# -------------
# BASIC AUTH
# -------------
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm SquidProxy
auth_param basic credentialsttl 2 hours
auth_param basic children 5

acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_access deny all

# -------------
# PRIVACY (aman, tanpa error)
# -------------
forwarded_for off
via on

# -------------
# CACHE
# -------------
cache_mem 64 MB
cache_dir ufs /var/spool/squid 1024 16 256
maximum_object_size 32 MB

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
EOF

echo "===> Buat file password Squid untuk basic auth..."
# -c = create file baru (overwrite kalau ada)
htpasswd -bc /etc/squid/passwords "$USERNAME" "$PASSWORD"

# Permission supaya hanya user 'proxy' yang bisa baca
chown proxy:proxy /etc/squid/passwords
chmod 640 /etc/squid/passwords

echo "===> Inisialisasi cache directory..."
if [[ ! -d /var/spool/squid ]]; then
  mkdir -p /var/spool/squid
fi
chown -R proxy:proxy /var/spool/squid

# HINDARI ERROR 'Squid is already running':
echo "===> Hentikan service squid kalau sedang jalan..."
systemctl stop squid 2>/dev/null || true

echo "===> Jalankan squid -z (init cache)..."
squid -z || true

echo "===> Enable & start ulang service squid..."
systemctl enable squid >/dev/null 2>&1 || true
systemctl restart squid

sleep 2

SYSTEMD_STATUS=$(systemctl is-active squid || echo "unknown")
if [[ "$SYSTEMD_STATUS" != "active" ]]; then
  echo "!!! Service squid tidak aktif. Cek log dengan:"
  echo "    journalctl -u squid -xe"
  exit 1
fi

echo "===> Ambil IP publik VPS..."
PUBLIC_IP="$(curl -s ifconfig.me || curl -s ipinfo.io/ip || hostname -I | awk '{print $1}')"

if [[ -z "$PUBLIC_IP" ]]; then
  echo "Tidak bisa mendeteksi IP publik. Isi IP VPS kamu manual."
  PUBLIC_IP="YOUR_VPS_IP"
fi

PROXY_URL="http://${USERNAME}:${PASSWORD}@${PUBLIC_IP}:${PORT}"

echo
echo "==========================================="
echo " Squid proxy berhasil di-setup dan jalan 🎉"
echo "==========================================="
echo
echo "Proxy URL (ini yang bisa kamu copy-paste):"
echo "${PROXY_URL}"
echo
echo "Contoh test:"
echo "  curl -x \"${PROXY_URL}\" https://httpbin.org/ip"
echo
echo "Cek log service:"
echo "  journalctl -u squid -f"
echo
