#!/usr/bin/env bash
set -e

# ==============================
# Simple Squid Proxy Installer
# Ubuntu / Debian (systemd)
# Usage:
#   sudo bash install_squid_proxy.sh [USERNAME] [PASSWORD] [PORT]
#
# Contoh:
#   sudo bash install_squid_proxy.sh user1 pass123 3128
#
# Kalau argumen kosong:
#   USERNAME default = proxyuser
#   PASSWORD default = proxypass
#   PORT     default = 3128
# ==============================

if [[ "$EUID" -ne 0 ]]; then
  echo "Jalankan script ini sebagai root (sudo)."
  exit 1
fi

USERNAME="${1:-proxyuser}"
PASSWORD="${2:-proxypass}"
PORT="${3:-3128}"

echo "===> Install Squid + apache2-utils..."
apt-get update -y
apt-get install -y squid apache2-utils curl

echo "===> Backup konfigurasi lama (kalau ada)..."
if [[ -f /etc/squid/squid.conf && ! -f /etc/squid/squid.conf.bak ]]; then
  cp /etc/squid/squid.conf /etc/squid/squid.conf.bak
  echo "Backup -> /etc/squid/squid.conf.bak"
fi

echo "===> Tulis konfigurasi Squid baru..."

cat >/etc/squid/squid.conf <<EOF
# =======================================
# Squid basic proxy with user:pass auth
# Generated by install_squid_proxy.sh
# Listen port
# =======================================
http_port ${PORT}

# -------------
# BASIC AUTH
# -------------
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm SquidProxy
auth_param basic credentialsttl 2 hours
auth_param basic children 5

acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_access deny all

# -------------
# PRIVACY
# -------------
forwarded_for off
request_header_access X-Forwarded-For deny all
via off

# -------------
# CACHE
# -------------
cache_mem 64 MB
cache_dir ufs /var/spool/squid 1024 16 256
maximum_object_size 32 MB

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log

dns_v4_first on
EOF

echo "===> Buat file password Squid untuk basic auth..."
# -c = create file baru (hanya sekali)
htpasswd -bc /etc/squid/passwords "$USERNAME" "$PASSWORD"

# Pastikan permission benar
chown proxy:proxy /etc/squid/passwords
chmod 640 /etc/squid/passwords

echo "===> Inisialisasi cache directory (kalau perlu)..."
if [[ ! -d /var/spool/squid ]]; then
  mkdir -p /var/spool/squid
  chown -R proxy:proxy /var/spool/squid
fi
squid -z || true

echo "===> Enable & restart service squid..."
systemctl enable squid >/dev/null 2>&1 || true
systemctl restart squid

sleep 2

SYSTEMD_STATUS=$(systemctl is-active squid || echo "unknown")
if [[ "$SYSTEMD_STATUS" != "active" ]]; then
  echo "!!! Service squid tidak aktif. Cek log dengan:"
  echo "    journalctl -u squid -xe"
  exit 1
fi

echo "===> Ambil IP publik VPS..."
PUBLIC_IP="$(curl -s ifconfig.me || curl -s ipinfo.io/ip || hostname -I | awk '{print $1}')"

if [[ -z "$PUBLIC_IP" ]]; then
  echo "Tidak bisa mendeteksi IP publik. Isi IP VPS kamu manual."
  PUBLIC_IP="YOUR_VPS_IP"
fi

PROXY_URL="http://${USERNAME}:${PASSWORD}@${PUBLIC_IP}:${PORT}"

echo
echo "==========================================="
echo " Squid proxy berhasil di-setup dan jalan 🎉"
echo "==========================================="
echo
echo "Proxy URL (log output yang kamu minta):"
echo "${PROXY_URL}"
echo
echo "Contoh test:"
echo "  curl -x \"${PROXY_URL}\" https://httpbin.org/ip"
echo
echo "Cek log service:"
echo "  journalctl -u squid -f"
echo
